spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: aks-java-api
    spec:
      containers:
      - name: aks-java-api
        image: hwacrdev001.azurecr.io/aks-java-api:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet: { path: /hello, port: 8080 }
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 6
        livenessProbe:
          httpGet: { path: /hello, port: 8080 }
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
