apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-java-api
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: aks-java-api
  template:
    metadata:
      labels:
        app: aks-java-api
    spec:
      containers:
      - name: aks-java-api
        # image injected by the pipeline (or replace ${IMAGE} with replacements)
        ports:
        - containerPort: 8080
        env:
        - name: APP_MESSAGE
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: APP_MESSAGE
        readinessProbe:
          httpGet:
            path: /hello
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /hello
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
